repos:
-   repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.7.0
    hooks:
    - id: isort
      args:
      - --check-only
#-   repo: https://github.com/pycqa/flake8
#    rev: 3.8.4
#    hooks:
#    -   id: flake8
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: check-yaml
-   repo: https://github.com/jendrikseipp/vulture
    rev: 'v2.6'  # or any later Vulture version
    hooks:
      - id: vulture
-   repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: 'v0.0.231' # Ruff version.
    hooks:
      - id: ruff
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: detect-private-key
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: check-added-large-files
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: check-merge-conflict
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: debug-statements
-   repo: https://github.com/pycqa/bandit
    rev: '1.7.5'
    hooks:
    -   id: bandit
        args: [-c, pyproject.toml]
        additional_dependencies: [".[toml]"]
