FROM remote-signer:latest

USER root
RUN	set -e;							\
	yum -y install	git-core python3-pip python3-devel	\
			gnutls-utils softhsm;			\
								\
	chown -R ec2-user /var/lib/softhsm;			\
								\
	pip3 install	pytest-cov;				\
								\
	: We install dyndb-mutex from source as 0.4.0;		\
	: does not support endpoint_url;			\
								\
	URL=git+https://github.com;				\
	URL="${URL}/chiradeep/dyndb-mutex";			\
	URL="${URL}@a39d06f06b5602d6fea98eea39247f337526c25c";	\
	URL="${URL}#egg=dyndbmutex";				\
								\
	pip3 install -e $URL;
USER ec2-user

WORKDIR /code
